config:
  text: Configurando ambiente de producción
  author: Wilmer
  email: N/A
  baseurl:
    endpoint:
      ms-products: http://ms-products
server:
  port: 8050
spring:
  application:
      name: ms-items

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

resilience4j:
  circuitbreaker:
    configs:
      default-config:
        sliding-window-size: 6
        failure-rate-threshold: 50
        wait-duration-in-open-state: 20s
        permitted-number-of-calls-in-half-open-state: 4
        slow-call-rate-threshold: 50
        slow-call-duration-threshold: 3s
    instances:
      items: # My circuitbreaker's name in itemController
        base-config: default-config
  timelimiter:
    configs:
      default-config:
        timeout-duration: 4s
    instances:
      items: # My circuitbreaker's name in itemController
        base-config: default-config